In [ ]:
The purpose of this notebook is to practice calcualtions related to the process of splitting decision trees.

In [2]:
import pandas as pd

In [6]:
tree_data= pd.read_excel('/Users/danielaquijano/Documents/GitHub/Machine-Learning-Course-Projects/sourcefiles/Tree_split_data.xlsx')

In [7]:
#Color Category has been changed. 0 represents white, 1 represents brown
tree_data

   Poisonous  Size Spots  Color
0          n     1     n      0
1          n     5     n      0
2          n     2     y      0
3          n     2     n      1
4          n     3     y      1
5          n     4     n      0
6          n     1     n      1
7          y     5     y      0
8          y     4     y      1
9          y     4     y      1
10         y     1     y      0
11         y     1     y      1